name: treehouse
description: "A peer to peer service app."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.3
  image_picker: ^1.1.2
  firebase_storage: ^12.3.6  
  cloud_firestore: ^5.5.0
  firebase_core: ^3.8.0
  firebase_database: ^11.1.6
  firebase_auth: 5.3.3
  intl: ^0.19.0 # Add the latest version here
  firebase_app_check: ^0.3.1+6


  # Cupertino Icons for iOS
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
