name: treehouse
description: "A peer to peer service app."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.3
  image_picker: ^1.1.2
  firebase_storage: ^12.3.6  
  cloud_firestore: ^5.5.0
  firebase_core: ^3.8.0
  firebase_database: ^11.1.6
  firebase_auth: ^5.3.3
  intl: ^0.19.0 # Updated to the latest compatible version
  firebase_app_check: ^0.3.1+6
  syncfusion_flutter_calendar: ^28.1.35
  provider: ^6.1.2 
  persistent_bottom_nav_bar: ^6.2.1
  url_launcher: ^6.3.1
  in_app_purchase: ^3.2.0
  google_fonts: ^6.2.1
  purchases_flutter: ^8.4.0
  custom_navigation_bar: ^0.8.2
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  video_player: ^2.9.2
  table_calendar: ^3.1.3
  flutter_stripe: ^11.3.0
  pay: ^3.0.1
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/fonts/    # Added fonts directory

  fonts:
    - family: Expressway
      fonts:
        - asset: assets/fonts/expressway.otf
          weight: 700

