name: treehouse
description: "A peer to peer service app."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.3
  image_picker: ^0.8.7+3
  firebase_storage: ^11.0.0  # Updated to a version that supports firebase_core ^2.0.0
  cloud_firestore: ^4.0.0
  firebase_core: ^2.32.0
  firebase_database: ^10.5.7

  # Cupertino Icons for iOS
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
