name: treehouse
description: "A peer to peer service app."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.3
  image_picker: ^0.8.5+3
  firebase_storage: ^12.3.6  
  cloud_firestore: ^5.5.0
  firebase_core: ^3.8.0
  firebase_database: ^11.1.6
  firebase_auth: ^5.3.3
  intl: ^0.19.0 # Updated to the latest compatible version
  firebase_app_check: ^0.3.1+6
  syncfusion_flutter_calendar: ^28.1.35
  

  # Cupertino Icons for iOS
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  video_player: ^2.9.2
  table_calendar: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
