// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaagiGw72xfwZbPhhBi4dZgZG1IQQtToE',
    appId: '1:545022405037:web:57e528a5489ca1c526d924',
    messagingSenderId: '545022405037',
    projectId: 'treehouse-c06f8',
    authDomain: 'treehouse-c06f8.firebaseapp.com',
    storageBucket: 'treehouse-c06f8.firebasestorage.app',
    measurementId: 'G-R5GNVLMCPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRIRA1yfQtNXchfGzz1rA4jT4WGfyoWMc',
    appId: '1:545022405037:android:472812c270740e7e26d924',
    messagingSenderId: '545022405037',
    projectId: 'treehouse-c06f8',
    storageBucket: 'treehouse-c06f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQGtFziEzTXg370zIsG8rwC0QRMEy5tV4',
    appId: '1:545022405037:ios:d1e80feb53a8622e26d924',
    messagingSenderId: '545022405037',
    projectId: 'treehouse-c06f8',
    storageBucket: 'treehouse-c06f8.firebasestorage.app',
    iosBundleId: 'com.example.workspace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQGtFziEzTXg370zIsG8rwC0QRMEy5tV4',
    appId: '1:545022405037:ios:d1e80feb53a8622e26d924',
    messagingSenderId: '545022405037',
    projectId: 'treehouse-c06f8',
    storageBucket: 'treehouse-c06f8.firebasestorage.app',
    iosBundleId: 'com.example.workspace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaagiGw72xfwZbPhhBi4dZgZG1IQQtToE',
    appId: '1:545022405037:web:4b378c959703f04a26d924',
    messagingSenderId: '545022405037',
    projectId: 'treehouse-c06f8',
    authDomain: 'treehouse-c06f8.firebaseapp.com',
    storageBucket: 'treehouse-c06f8.firebasestorage.app',
    measurementId: 'G-PM6VE8YC0K',
  );
}
